version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build stage...
  build:
    commands:
      - echo Building the application...
      - npm run build || echo "No build script found. Skipping..."
  post_build:
    commands:
      - echo Build complete. Preparing artifacts...

artifacts:
  files:
    - '**/*'
  discard-paths: no
